<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/SQL-Malumotlar-ombori/blob/main/SQL2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import sqlite3 as sql

In [27]:
db = sql.connect("newdb.db")
cursor = db.cursor()

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df.head()

,Entity,Code,Year,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

In [49]:
cols = ['country','code','year','coal','gas','hydro','renewable_other','solar','oil','wind','nuclear']
df.columns = cols
df.head(-5)

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,Afghanistan,AFG,2000,0.00000,0.155,0.312,0.000,0.0000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.00000,0.094,0.498,0.000,0.0000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.00000,0.132,0.555,0.000,0.0000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.00000,0.309,0.630,0.000,0.0000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.00000,0.329,0.565,0.000,0.0000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6231,Zimbabwe,ZWE,2010,2.60568,0.000,5.741,0.094,0.0000,0.0,0.0,0.0
6232,Zimbabwe,ZWE,2011,3.64814,0.000,5.149,0.131,0.0004,0.0,0.0,0.0
6233,Zimbabwe,ZWE,2012,3.42348,0.000,5.336,0.168,0.0020,0.0,0.0,0.0
6234,Zimbabwe,ZWE,2013,4.14070,0.000,4.946,0.166,0.0030,0.0,0.0,0.0
6235,Zimbabwe,ZWE,2014,4.18112,0.000,5.377,0.144,0.0050,0.0,0.0,0.0

In [38]:
df.to_sql('select',db)

6241

In [39]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('elect',), ('select',)]

In [41]:
cursor.execute("PRAGMA table_info(elect);")
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'Entity', 'TEXT', 0, None, 0),
 (2, 'Code', 'TEXT', 0, None, 0),
 (3, 'Year', 'INTEGER', 0, None, 0),
 (4, 'Electricity from coal (TWh)', 'REAL', 0, None, 0),
 (5, 'Electricity from gas (TWh)', 'REAL', 0, None, 0),
 (6, 'Electricity from hydro (TWh)', 'REAL', 0, None, 0),
 (7, 'Electricity from other renewables (TWh)', 'REAL', 0, None, 0),
 (8, 'Electricity from solar (TWh)', 'REAL', 0, None, 0),
 (9, 'Electricity from oil (TWh)', 'REAL', 0, None, 0),
 (10, 'Electricity from wind (TWh)', 'REAL', 0, None, 0),
 (11, 'Electricity from nuclear (TWh)', 'REAL', 0, None, 0)]

In [54]:
query = "SELECT * FROM select WHERE country = 'Uzbekistan'"
pd.read_sql(query,db)

DatabaseError: Execution failed on sql 'SELECT * FROM select WHERE country = 'Uzbekistan'': near "select": syntax error

In [55]:
query = """
CREATE TABLE IF NOT EXISTS worldpop(
  rank INT,
  country TEXT PRIMARY KEY,
  density DOUBLE,
  population DOUBLE NOT NULL,
  area INT NOT NULL
);
"""
cursor.execute(query)

In [56]:
db.commit()

In [57]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('elect',), ('select',), ('worldpop',)]

In [58]:
cursor.execute("PRAGMA table_info(worldpop);")
cursor.fetchall()

[(0, 'rank', 'INT', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 1),
 (2, 'density', 'DOUBLE', 0, None, 0),
 (3, 'population', 'DOUBLE', 1, None, 0),
 (4, 'area', 'INT', 1, None, 0)]

In [59]:
query = "INSERT INTO worldpop VALUES (1, 'Macau', 21946.4667, 658.3940,30)"
cursor.execute(query)
db.commit()

In [60]:
cursor.execute("SELECT * FROM worldpop")
cursor.fetchall()

[(1, 'Macau', 21946.4667, 658.394, 30)]

In [61]:
query= "INSERT INTO worldpop (country, population, area) VALUES ('Uzbekistan', 33935.7630,447400)"
cursor.execute(query)
db.commit()

In [62]:
pd.read_sql("SELECT * FROM worldpop",db)

   rank     country     density  population    area
0   1.0       Macau  21946.4667     658.394      30
1   NaN  Uzbekistan         NaN   33935.763  447400

In [63]:
query = "UPDATE worldpop SET rank = 133, density=75.8511 WHERE country = 'Uzbekistan'"

In [64]:
cursor.execute(query)
db.commit()

In [65]:
pd.read_sql("SELECT * FROM worldpop",db)

   rank     country     density  population    area
0     1       Macau  21946.4667     658.394      30
1   133  Uzbekistan     75.8511   33935.763  447400

In [66]:
query = "DELETE FROM worldpop WHERE country = 'Macau'"
cursor.execute(query)
db.commit()

In [67]:
pd.read_sql("SELECT * FROM worldpop",db)

   rank     country  density  population    area
0   133  Uzbekistan  75.8511   33935.763  447400

In [79]:
query = """
CREATE TABLE IF NOT EXISTS worldpop(
rank INT,
country TEXT PRIMARY KEY,
density DOUBLE,
population DOUBLE NOT NULL,
area INT NOT NULL
);
"""
cursor.execute(query)
db.commit()

In [80]:
uz=df[df.country=="Uzbekistan"]
print(uz)

         country code  year       coal        gas     hydro  renewable_other  \
5964  Uzbekistan  UZB  2000  11.602405  25.523451  5.817000              0.0
5965  Uzbekistan  UZB  2001  11.766320  25.884038  5.899000              0.0
5966  Uzbekistan  UZB  2002  12.214374  26.869686  6.124000              0.0
5967  Uzbekistan  UZB  2003  11.833513  26.031852  7.544000              0.0
5968  Uzbekistan  UZB  2004  11.595776  25.508869  8.920000              0.0
5969  Uzbekistan  UZB  2005  11.490919  25.278199  8.838000              0.0
5970  Uzbekistan  UZB  2006  11.827788  26.019258  4.653000              0.0
5971  Uzbekistan  UZB  2007  12.051665  26.511751  4.610000              0.0
5972  Uzbekistan  UZB  2008  10.774273  23.701692  4.443000              0.0
5973  Uzbekistan  UZB  2009   9.084625  28.017530  6.418000              0.0
5974  Uzbekistan  UZB  2010   9.792027  30.199200  8.110000              0.0
5975  Uzbekistan  UZB  2011  10.534094  32.487781  5.646000              0.0
5976  Uzbekistan  UZB  2012  10.365016  31.966333  6.586000              0.0
5977  Uzbekistan  UZB  2013  10.939346  33.737603  5.647000              0.0
5978  Uzbekistan  UZB  2014  11.112674  34.272157  6.014000              0.0
5979  Uzbekistan  UZB  2015  10.519789  35.780629  6.998000              0.0
5980  Uzbekistan  UZB  2016  10.783891  36.678911  7.254000              0.0
5981  Uzbekistan  UZB  2017  10.998707  37.409561  8.343000              0.0
5982  Uzbekistan  UZB  2018  11.853192  40.315893  5.838030              0.0
5983  Uzbekistan  UZB  2019  12.297660  41.827647  5.451373              0.0
5984  Uzbekistan  UZB  1985        NaN        NaN  5.431443              0.0
5985  Uzbekistan  UZB  1986        NaN        NaN  4.618273              0.0
5986  Uzbekistan  UZB  1987        NaN        NaN  6.770521              0.0
5987  Uzbekistan  UZB  1988        NaN        NaN  7.163847              0.0
5988  Uzbekistan  UZB  1989        NaN        NaN  5.502153              0.0
5989  Uzbekistan  UZB  1990        NaN        NaN  6.648000              0.0
5990  Uzbekistan  UZB  1991        NaN        NaN  6.031000              0.0
5991  Uzbekistan  UZB  1992        NaN        NaN  6.281000              0.0
5992  Uzbekistan  UZB  1993        NaN        NaN  7.358000              0.0
5993  Uzbekistan  UZB  1994        NaN        NaN  7.156000              0.0
5994  Uzbekistan  UZB  1995        NaN        NaN  6.188000              0.0
5995  Uzbekistan  UZB  1996        NaN        NaN  6.525000              0.0
5996  Uzbekistan  UZB  1997        NaN        NaN  5.777000              0.0
5997  Uzbekistan  UZB  1998        NaN        NaN  5.758000              0.0
5998  Uzbekistan  UZB  1999        NaN        NaN  5.692000              0.0

         solar       oil  wind  nuclear
5964  0.000000  1.380143   0.0      0.0
5965  0.000000  1.399642   0.0      0.0
5966  0.000000  1.452939   0.0      0.0
5967  0.000000  1.407634   0.0      0.0
5968  0.000000  1.379355   0.0      0.0
5969  0.000000  1.366882   0.0      0.0
5970  0.000000  1.406953   0.0      0.0
5971  0.000000  1.433584   0.0      0.0
5972  0.000000  1.281634   0.0      0.0
5973  0.000000  1.080645   0.0      0.0
5974  0.000000  1.164793   0.0      0.0
5975  0.000000  1.253064   0.0      0.0
5976  0.000000  1.232952   0.0      0.0
5977  0.001996  1.301270   0.0      0.0
5978  0.002046  1.321888   0.0      0.0
5979  0.002176  1.251363   0.0      0.0
5980  0.004643  1.282778   0.0      0.0
5981  0.006290  1.308332   0.0      0.0
5982  0.006827  1.409975   0.0      0.0
5983  0.006827  1.462846   0.0      0.0
5984  0.000000       NaN   0.0      0.0
5985  0.000000       NaN   0.0      0.0
5986  0.000000       NaN   0.0      0.0
5987  0.000000       NaN   0.0      0.0
5988  0.000000       NaN   0.0      0.0
5989  0.000000       NaN   0.0      0.0
5990  0.000000       NaN   0.0      0.0
5991  0.000000       NaN   0.0      0.0
5992  0.000000       NaN   0.0      0.0
5993  0.000000       NaN   0.0      0.0
5994  0.000000       NaN   0.0      0.0
5995  0.000000       NaN   0.0      0.0
5996  0.000000       NaN   0.0      0.0
5997  0.000000       NaN   0.0      0.0
5998  0.000000       NaN   0.0      0.0

In [81]:
rank = uz.index.values[0]
country = uz.at[rank, 'country']
density = uz.at[rank, 'density']
population = uz.at[rank, 'pop2021']
area = uz.at[rank, 'area']
print(f"{rank=}, {country=}, {density=}, {population=}, {area=}")

KeyError: 'density'

In [75]:
query = f"""
INSERT INTO worldpop VALUES ({rank}, '{country}')
"""
cursor.execute(query)
db.commit()

OperationalError: table worldpop has 5 columns but 2 values were supplied