<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/SQL-Malumotlar-ombori/blob/main/SQL_1_dars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [2]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2024-05-28 10:21:11--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3037::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.1s

2024-05-28 10:21:11 (3.06 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [3]:
!unzip chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [5]:
db = sql.connect("chinook.db")
cursor=db.cursor()

In [7]:
cursor.execute("SELECT name FROM sqlite_master WHERE type = 'table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [11]:
cursor.execute("SELECT COUNT (*) FROM employees")
cursor.fetchone()

(8,)

In [12]:
cursor.execute("PRAGMA table_info(customers);")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

In [15]:
cursor.execute("SELECT * FROM customers")
mijozlar = cursor.fetchall()

In [23]:
komanda = "SELECT CustomerId,FirstName, LastName,Phone , Country FROM customers"
df = pd.read_sql(komanda , db, index_col='CustomerId' )
df.head()

            FirstName     LastName               Phone         Country
CustomerId
1                Luís    Gonçalves  +55 (12) 3923-5555          Brazil
2              Leonie       Köhler    +49 0711 2842222         Germany
3            François     Tremblay   +1 (514) 721-4711          Canada
4               Bjørn       Hansen     +47 22 44 22 22          Norway
5           František  Wichterlová    +420 2 4172 5555  Czech Republic

In [29]:
# komanda = "SELECT CustomerId,FirstName, LastName,Phone , Country FROM customers ORDER BY LastName"
# df = pd.read_sql(komanda , db, index_col='CustomerId' )
# df.head()


komanda = "SELECT CustomerId, FirstName,LastName, Phone, Country From customers ORDER BY LastName"
df = pd.read_sql(komanda, db, index_col="CustomerId")
df.head()

           FirstName LastName               Phone Country
CustomerId
12           Roberto  Almeida  +55 (21) 2271-7000  Brazil
28             Julia  Barnett   +1 (801) 531-7272     USA
39           Camille  Bernard  +33 01 49 70 65 65  France
18          Michelle   Brooks   +1 (212) 221-3546     USA
29            Robert    Brown   +1 (416) 363-8888  Canada

In [32]:
query = "SELECT DISTINCT Country FROM customers"
cursor.execute(query)
cursor.fetchall()

[('Brazil',),
 ('Germany',),
 ('Canada',),
 ('Norway',),
 ('Czech Republic',),
 ('Austria',),
 ('Belgium',),
 ('Denmark',),
 ('USA',),
 ('Portugal',),
 ('France',),
 ('Finland',),
 ('Hungary',),
 ('Ireland',),
 ('Italy',),
 ('Netherlands',),
 ('Poland',),
 ('Spain',),
 ('Sweden',),
 ('United Kingdom',),
 ('Australia',),
 ('Argentina',),
 ('Chile',),
 ('India',)]

In [27]:
pd.read_sql(query,db)

           Country
0           Brazil
1          Germany
2           Canada
3           Norway
4   Czech Republic
5          Austria
6          Belgium
7          Denmark
8              USA
9         Portugal
10          France
11         Finland
12         Hungary
13         Ireland
14           Italy
15     Netherlands
16          Poland
17           Spain
18          Sweden
19  United Kingdom
20       Australia
21       Argentina
22           Chile
23           India

In [39]:
query = 'SELECT * FROM customers WHERE country = "USA" AND State="NY" ORDER BY Lastname'
pd.read_sql(query, db)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3